### ISSUE TITLE
Exception while saving Maple Mono NF

### ISSUE THREAD

**Issue by SsparKluo** [MuTsunTsai/fontfreeze#10]
Here is the [github repo](https://github.com/subframe7536/maple-font) for the font

Here is the error message:
```
Error: Traceback (most recent call last):
  File "<exec>", line 156, in processFont
  File "<exec>", line 159, in main
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 711, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 733, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 207, in compile
    chunk = table.compile(ttFont)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 400, in compile
    gids = array.array("B", valueList)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: unsigned byte integer is greater than maximum

    at i.port1.onmessage (main.js:1:1432)
```

Procedure to reproduce the error (by edge or firefox):
1. download the newest version of maple mono font and open it
2. select any of cv01~cv04 feature
3. generate the font with `Apply substitution by single-glyph features.` selected and get the error

Btw, the fontfreezer works well with the older version font.

**Comment by MuTsunTsai** [comment]
Basically the same issue as #8. "NF" stands for Nerd Font here, and it is known that FontFreeze will get into this error with Nerd Fonts. A workaround is that you can freeze the regular font first, and then patch it with Nerd Font.

**Comment by MuTsunTsai** [comment]
I see. I think then it has to do with #7, which leads to an [issue](https://github.com/subframe7536/maple-font/issues/96) in MapleMono that supposedly has been fixed. I suggest that you inform them that the issue persists.

**Comment by SsparKluo** [comment]
Thanks a lot, will do.
