### ISSUE TITLE
AssertionError when saving if "Target feature for activation" is empty

### ISSUE THREAD

**Issue by benblank** [MuTsunTsai/fontfreeze#14]
I was trying to customize JuliaMono and, as `calt` was one of the features I was looking to remove and it was present in the "Target feature for activation" field, I removed it there as well. When clicking the "Generate Font!" button, an `AssertionError` modal appeared (see collapsed section below).

After some fiddling, I was able to isolate the problem to having an empty target feature field plus at least one feature being applied/enabled (blue checkbox). The font used didn't seem to matter, but I only had a couple of fonts handy to test with (JuliaMono and Hack).

<details><summary>AssertionError: (b'', 'str', 39, 'FeatureRecord[]', 'FeatureList')</summary>

```text
An error occur: Traceback (most recent call last):
  File "<exec>", line 155, in processFont
  File "<exec>", line 158, in main
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 710, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 732, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 155, in compile
    self.table.compile(writer, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1100, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 753, in write
    value.compile(subWriter, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1062, in compile
    conv.writeArray(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 216, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 634, in write
    value.compile(writer, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1100, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 423, in write
    writer.writeTag(value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 784, in writeTag
    assert len(tag) == 4, tag
           ^^^^^^^^^^^^^
AssertionError: (b'', 'str', 39, 'FeatureRecord[]', 'FeatureList')
```

</details>

**Comment by MuTsunTsai** [comment]
That's not how it works. Just mark the `calt` with an ❌ while leave the `Target feature for activation` as it is, and the font will build.

**Comment by benblank** [comment]
Yeah, I figured that out afterward. I was just thinking that it would be nice if there were a friendly error message saying that the target feature field shouldn't be empty rather than a stack trace. 🙂

**Comment by MuTsunTsai** [comment]
The friendly error message is now shipped with v1.10.3.
