### ISSUE TITLE
Error when trying to freeze JetBrains Mono

### ISSUE THREAD

**Issue by th-bu** [MuTsunTsai/fontfreeze#4]
I get the following error when I try to freeze the current version (2.303) of JetBrains Mono:

```
An error occur: Traceback (most recent call last):
  File "<exec>", line 145, in processFont
  File "<exec>", line 149, in main
  File "/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 184, in save
    writer_reordersTables = self._save(tmp)
  File "/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 224, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 647, in _writeTable
    tabledata = self.getTableData(tag)
  File "/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 103, in compile
    self.table.compile(writer, font)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 904, in compile
    conv.writeArray(writer, font, table, value)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 197, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 510, in write
    value.compile(writer, font)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "/lib/python3.10/site-packages/fontTools/ttLib/tables/otTables.py", line 498, in compile
    assert featureParamTypes.get(writer['FeatureTag']) == self.__class__, "Wrong FeatureParams type for feature '%s': %s" % (writer['FeatureTag'], self.__class__.__name__)
AssertionError: ("Wrong FeatureParams type for feature 'DELT': FeatureParamsStylisticSet", 'FeatureParamsStylisticSet', 'Feature', 38, 'FeatureRecord[]', 'FeatureList')
```

I used `JetBrainsMono-Regular.ttf` and checked `ss19` and `zero`. I kept everything else as default.

**Comment by th-bu** [comment]
Thanks for the fix, I don't get the error anymore and the features frozen in the font.

**Comment by th-bu** [comment]
Just tested a bit more and Windows doesn't recognize the Bold Italic version of the font after I used your tool.

I tested this with Cascadia Code and JetBrains Mono and in both cases the Bold Italic style is missing in Windows after the installation of the font.

Should I open a new issue for this?

**Comment by MuTsunTsai** [comment]
Yes, please do; and I might need more details as for what happened and what is expected. I will close this issue for now.

**Comment by MuTsunTsai** [comment]
Yeah, please do, just for a reminder of this issue so that I can take care of it later.

**Comment by th-bu** [comment]
I just tried to use the frozen font for the first time in Rider and here I now have the _Bold Italic_ style as the _Bold_ style. So I guess you really have to go the way of #5. When I find the time I will do a post with screenshots etc.
