### ISSUE TITLE
[Bug] got an error when generating font

### ISSUE THREAD

**Issue by zhaihao** [MuTsunTsai/fontfreeze#8]
the settings
![2](https://github.com/MuTsunTsai/fontfreeze/assets/4202032/4e2c441e-1071-48c7-9e3e-413620bada74)

and my font file:
[MapleMonoSCNFNerdFont-Regular.ttf.zip](https://github.com/MuTsunTsai/fontfreeze/files/11469073/MapleMonoSCNFNerdFont-Regular.ttf.zip)

then I got an error:

```log
An error occur: Traceback (most recent call last):
  File "<exec>", line 154, in processFont
  File "<exec>", line 157, in main
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 711, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 733, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/O_S_2f_2.py", line 161, in compile
    self.panose = sstruct.pack(panoseFormat, self.panose)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/misc/sstruct.py", line 66, in pack
    obj = obj.__dict__
          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '__dict__'
```

**Comment by MuTsunTsai** [comment]
It appears that MapleMono font in particular is not exactly created according to specs and could lead to various issues (such as #7) with font processing softwares. I could investigate into this when I have time, but likely this might be an issue of FontFreeze.

**Comment by MuTsunTsai** [comment]
@zhaihao Ah, that's good to know! I've added that remark in README.

**Comment by Finii** [comment]
Well, it seems an ancient version of the Nerd Fonts `font-patcher` is used by maple-font.
More importantly, and probably the reason for the bug, is to use a recent (i.e. Release 2023.01.01) `fontforge` together with the `font-patcher`. There have been various bugfixes in `fontforge` that resulted in broken tables.
