### ISSUE TITLE
Exception while saving Source Code Pro font

### ISSUE THREAD

**Issue by th-bu** [MuTsunTsai/fontfreeze#9]
I get the following exception when I try to freeze Source Code Pro.

```
An error occur: Traceback (most recent call last):
  File "<exec>", line 154, in processFont
  File "<exec>", line 157, in main
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 711, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 733, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 155, in compile
    self.table.compile(writer, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1089, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 754, in write
    value.compile(subWriter, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1051, in compile
    conv.writeArray(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 216, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 634, in write
    value.compile(writer, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1089, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 754, in write
    value.compile(subWriter, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1089, in compile
    conv.write(writer, font, table, value)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otConverters.py", line 754, in write
    value.compile(subWriter, font)
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/otTables.py", line 517, in compile
    featureParamTypes.get(writer["FeatureTag"]) == self.__class__
AssertionError: ("Wrong FeatureParams type for feature 'calt': FeatureParamsStylisticSet", 'FeatureParamsStylisticSet', 'Feature', 237, 'FeatureRecord[]', 'FeatureList')
```

Steps to reproduce:
* Download the ttf version of the font: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.042R-u%2F1.062R-i%2F1.026R-vf
* Load SourceCodePro-Regular.ttf in the freezer
* Select ss07 or any other stylistic set
* Click "Generate font!"
* You will get the exception and a 0 byte file is saved to the system.

I tried this with Firefox, Chrome and Edge.

**Comment by MuTsunTsai** [comment]
Hello and thanks for the detailed report! This font is interesting that it doesn't have `calt` in it at all, and apparently that is what causes the trouble. I've made a fix to it and it should work now, please try it!

**Comment by th-bu** [comment]
Thanks for the fix, it's working now 👍
